name: Automatic Update
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Thomas'
          git config --global user.email 'tpucci@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020.git
          git fetch upstream

          git checkout master
          git merge --no-edit upstream/master
          git push origin master
